### ISSUE TITLE
Make issue templates for common types

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#10]
Perhaps we can even try the brand new yaml based forms? 

https://www.youtube.com/watch?v=qQE1BUkf2-s

What kinds of issues do we want templates for?

First guess is:

- Bug report (with options that can sort out content issues nicely)
- Feature request

**Comment by Abbe98** [comment]
Oh, the forms looks cool!

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

We should also have a generic comment somewhere to direct people with general questions to discussions/Wikidata.

**Comment by Ainali** [comment]
> We should also have a generic comment somewhere to direct people with general questions to discussions/Wikidata.

That's a good idea!

**Comment by Abbe98** [comment]
I have added this to Sprint 2 as it would be nice to have it in place for upcoming workshops, presentations, etc.

**Comment by Abbe98** [comment]
Here we go: https://github.com/govdirectory/website/issues/new/choose

One issue that remains is that we can't set labels as our labels contain emoji.
