### ISSUE TITLE
Investigate CSV issues on Windows

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#101]
Two users have reported that Excel will fail to recognize the CSV as a CSV.

It's known to work on Linux with Libreoffice, consider investigating on MacOS.

**Comment by Abbe98** [comment]
> it depends on the region settings in control panel if comma or semicolon is used as separator. So the same CSV file may open correctly on one computer but on another computer not.

> for example on a german Windows by default semicolon must be used as separator while comma does not work.

https://stackoverflow.com/a/40807218/2280074

https://kb.paessler.com/en/topic/2293-i-have-trouble-opening-csv-files-with-microsoft-excel-is-there-a-quick-way-to-fix-this

So Excel appears to not support opening CSV files if you are in Europe.

**Comment by Abbe98** [comment]
In a recent project I selected TSV as an output format instead of CSV for this reason, maybe we should switch as well?

**Comment by Ainali** [comment]
That might make sense.
