### ISSUE TITLE
govdirectory.org should set the Referrer-Policy header

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#111]
### The feature

No external sites we link to should be allowed to see the origin of a user following the link. Therefore, `Referrer-Policy `should be set to `no-referrer`.

### Why?

For privacy reasons.

### Examples and inspiration

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

### Notes

Because we serve Govdirectory from the Github CDN we can't set custom headers so this tasked is blocked by #33.

**Comment by RVA2869** [comment]
@Abbe98 Is this issue still relevant? Apparently (since October 2021) if there is no explicit header present, the default policy is applied. Which is `<meta name="referrer" content="strict-origin-when-cross-origin">`

**Comment by Abbe98** [comment]
No if that's the case we can close this!

**Comment by RVA2869** [comment]
> No if that's the case we can close this!

[https://web.dev/articles/referrer-best-practices#default](https://web.dev/articles/referrer-best-practices#default)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#strict-origin-when-cross-origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#strict-origin-when-cross-origin)

**Comment by Abbe98** [comment]
Amazing!
