### ISSUE TITLE
"Lead by" should probably be "Led by"?

### ISSUE THREAD

**Issue by enterprisey** [govdirectory/website#123]
### What happened?

When it says an agency or something is "lead by" an entity, I suspect the verb "lead" should be conjugated to be "led" instead (yeah, it's a homophone, I apologize on behalf of the English language).

### What browsers are you seeing the problem on?

Firefox

**Comment by Ainali** [comment]
Thank you, and yes, I believe you are right!

**Comment by Abbe98** [comment]
Thank you @enterprisey! :star:  The changes will go live later today as we will deploy some other changes at the same time.
