### ISSUE TITLE
Add phone number for institutions

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#127]
### The feature

We should add [phone number (P1329)](https://www.wikidata.org/wiki/Property:P1329) to the infoboxes of the institutions. 

### Why?

Our new catchphrase is "The easiest way to contact your government." and many people will probably use our site will on the phone. Our interviews also shows that activists are very willing to call the agencies.

**Comment by Abbe98** [comment]
I think we should only display phone numbers if there is a reference as you can't see on the number itself that it's somehow connected to the institution in question.
