### ISSUE TITLE
Add README at the Github organization level

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#130]
### Description

Since a few weeks, it's possible to add a README file at the organization level. We should add one that gives an overview of our repositories and the project in general.

https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/

**Comment by Abbe98** [comment]
Contents:

 - Link to website.
 - A quick blurb on what this is.
 - Link to the main repository (this one).
 - Link to Wikidata.

It would be very cool if we could have a visual SVG-based one. Additionally, it would be cool if we could display stats from #135 by having the SVG generated by Snowman and published on Govdirectory(but that's a future thing).

**Comment by Ainali** [comment]
I got [something up](https://github.com/govdirectory/.github/tree/main/profile) that we can iterate on.
