### ISSUE TITLE
Add a maskable icon

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#136]
### Description

We provide plenty of icons for mobile devices but we could also provide an adaptive one:
https://web.dev/maskable-icon/

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it.

**Comment by RVA2869** [comment]
@Ainali @Abbe98 Any preference?  This is a first draft.
![maskable-icon](https://github.com/govdirectory/website/assets/144518518/9c396196-67cb-4bcf-8347-0f22dad04d36)
![maskable-icon v2](https://github.com/govdirectory/website/assets/144518518/5797c4ab-9790-43f9-8be0-ef734a06c94e)
