### ISSUE TITLE
Make a high level roadmap

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#14]
Let's put together a high level roadmap of what we want to do and in roughly what order we want to it in. We can document it and ROADMAP.md and refer to it from both the readme and contributing file.

**Comment by Abbe98** [comment]
Maybe use a board like: https://github.com/orgs/govdirectory/projects/2 ? We can use notes for high-level things and issues for more defined tasks.

**Comment by Ainali** [comment]
I think a board will be very useful but this could be even more high level almost carving out what the idea means in practice. It should be of so low detail that we hopefully don't need to update it very often at all.

**Comment by Ainali** [comment]
After discussion in today's meeting. Let's use the board, milestones alongside with the MVP we defined today. @Abbe98 is it enough by capturing "As an MVP we want to create an working website where people can search, filter and add data about Swedish public institutions and their social media accounts." as text somewhere (and then the other parts could become issues with the Demo day milestone)?

**Comment by Abbe98** [comment]
Yes Sounds good to me!
