### ISSUE TITLE
Fix OG image

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#141]
Right now the Facebook preview looks like this:
![Skärmbild från 2021-10-07 21-07-29](https://user-images.githubusercontent.com/5566159/136447263-a3972ac6-3404-4ddd-9565-a00555fb89ee.png)

We should have a better image set.

**Comment by Abbe98** [comment]
Related Open Graph documentation: https://ogp.me/#structured

Regarding size we should probably follow Facebook's recommendations:
https://developers.facebook.com/docs/sharing/webmasters/images/

**Comment by Abbe98** [comment]
"Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. "

**Comment by Abbe98** [comment]
This one might be resolved. @Ainali?

**Comment by Ainali** [comment]
Yes, I think we can close this for now.
