### ISSUE TITLE
Make the "Download" button more descriptive

### ISSUE THREAD

**Issue by dpriskorn** [govdirectory/website#145]
### Description

![bild](https://user-images.githubusercontent.com/68460690/138263409-0ba4c837-b7ff-42de-b62c-48dced92740c.png)
After pressing Download I was curious what I would get. Maybe a label like "Download the data below as CSV" or something like that would be more clear?

**Comment by Abbe98** [comment]
In case someone wants to pick this one up note that following #101, the download now gives users TSV, not CSV.
