### ISSUE TITLE
Update Integraality lists to include email, and phone numbers

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#151]
### The feature

The Integraality lists should include stats about phone numbers and email addresses.

### Why?

We currently include popular social media platforms in the stats but to our users, email/phone numbers are just as important and we should signal this to data contributors.

**Comment by Ainali** [comment]
Here is an example of a dashboard that becomes relevant once the group of agencies has three stars or more: https://www.wikidata.org/wiki/Wikidata:WikiProject_Govdirectory/Sweden/Coverage_of_second_level_agencies

**Comment by Ainali** [comment]
I have [added documentation](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_Govdirectory&diff=prev&oldid=1934133967) now.
