### ISSUE TITLE
Make proposal for FOI request form URL

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#17]
**Mandatory property:** object has role unofficial/official 

**Related Links:**
handlingar.se/
https://www.foia.gov/?id=15505805-6876-4fc8-9101-fb45c5ff32d0&type=agency
https://www.wikidata.org/wiki/Property:P8167

**Comment by Abbe98** [comment]
Draft: https://www.wikidata.org/wiki/Wikidata:Property_proposal/URL_for_freedom_of_information_requests

**Comment by Abbe98** [comment]
> Draft: https://www.wikidata.org/wiki/Wikidata:Property_proposal/URL_for_freedom_of_information_requests

Now published.

**Comment by Ainali** [comment]
[Done](https://www.wikidata.org/w/index.php?title=Wikidata:Property_proposal/URL_for_freedom_of_information_requests&oldid=prev&diff=1552491253) with [P10214](https://www.wikidata.org/wiki/Property:P10214)!
