### ISSUE TITLE
Prominent "error message"

### ISSUE THREAD

**Issue by miroli** [govdirectory/website#179]
### Description

The "Found an error?" message is quite big and and prominent. In combination with the background color I get the feeling that I'm met with an error message. Perhaps it could be rephrased to something along the lines of "Improve this data"?
<img width="1000" alt="bild" src="https://user-images.githubusercontent.com/1508133/149762391-3bde34e6-6129-4b13-b820-dab4ac01510f.png">

**Comment by Ainali** [comment]
Thank you, that is great feedback! 

Perhaps with #178 adding a new button, we should also address this issue to make room for more topical actions front and center and move the Wikidata to the top right corner. It could also then perhaps also be a bit more discrete. 

I guess the question is if it should be a call to action, or rather serve more of an explaining provenance purpose.

**Comment by Abbe98** [comment]
Related to #87

**Comment by Abbe98** [comment]
#180 removes this for agency pages, the problem still exists for country pages which would be harmonized with topic pages design-wise at one point.

**Comment by Abbe98** [comment]
I have noticed that Google sometimes thinks these are soft 404s.
