### ISSUE TITLE
Get complete coverage of environmental protection agencies

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#18]
We want data to be filterable on what type of agency it is. Environmental protection agencies will be the one to use in the demo.

- [ ] Figure out how to model this type of data in Wikidata
- [ ] Add the data for all countries
  - [ ] Give instructions to Wikimedians for Sustainable Development

**Comment by Abbe98** [comment]
Closing this as it isn't compatible with the per-country approach we took.
