### ISSUE TITLE
URLs to online accounts break if the id/username is not the last part of the URL

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#193]
### What happened?

Social media services for which account URLs do not end with the username/id stored in Wikidata, Govdirectory will fail to produce a working URL.

The issue is because of the following line and affects major platforms like LinkedIn and Instagram.

https://github.com/govdirectory/website/blob/1106b32c9da97bb1daee75cf2c25154369bfb642/queries/account-data.rq#L23

### What browsers are you seeing the problem on?

Other (describe above)

**Comment by Ainali** [comment]
Do we have an example? I thought both LinkedIn and Instagram had the usernames in the end of the URL.

**Comment by Abbe98** [comment]
Example: https://www.govdirectory.org/sweden/Q33075406/

Technically they have a `/` at the end.

Rather than use `SUBSTR`/`CONCAT` to replace `$1` we should use `REPLACE`.
