### ISSUE TITLE
Add a Govdirectory icon/link template to Wikidata

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#196]
### Description

It would be great to be able to use the list of countries(and maybe on individual country pages too?) on the Wikiproject page to get an overview of what's already on Govdirectory.

One way to do this could be to have a small template that just takes a QID and renders a small Govdirectory icon which is also a link to the relevant Govdirectory.org page. That could be added next to each of the countries added to Govdirectory.org.

**Comment by Ainali** [comment]
That is a great idea!

**Comment by Ainali** [comment]
The template could also add a category as well.

**Comment by Ainali** [comment]
First rough draft: https://www.wikidata.org/wiki/Template:Govdirectory_published

On country project pages, would we want to add this template next to each type of agency?

And in the overview, should we add it after the stars on each level we have something published?

**Comment by Abbe98** [comment]
> On country project pages, would we want to add this template next to each type of agency?

Yes, I think that would make sense.

> And in the overview, should we add it after the stars on each level we have something published?

I think we can start with that and see how it works.

**Comment by Ainali** [comment]
[Template:Govdirectory_published](https://www.wikidata.org/wiki/Template:Govdirectory_published) have now been added on both the overview page and on the subpages. Hopefully, that makes it possible to understand exactly which agency types have been published.

[Template:Gov directory/Jurisdiction summary](https://www.wikidata.org/wiki/Template:Gov_directory/Jurisdiction_summary) have been extended with two parameters. If `published` is set to yes, it creates a link to the page on govdirectory (with the help of the second parameter `url-name`) and adds it to [Category:WikiProject Govdirectory - published on website](https://www.wikidata.org/wiki/Category:WikiProject_Govdirectory_-_published_on_website).
