### ISSUE TITLE
Check for dead position holders

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#217]
### Description

As [reported on Wikidata](https://www.wikidata.org/w/index.php?title=Wikidata_talk:WikiProject_Govdirectory&diff=1654416807&oldid=1633257072), there was a few cases of position holders that had been dead for hundreds of years. While the data in Wikidata wasn't good, they were missing start and end dates on the position, we could perhaps add a check that the position holder is alive. Should we add
```
MINUS { ?person wdt:P570 [] }
```
to [organization-optional.rq](https://github.com/govdirectory/website/blob/main/queries/organization-optional.rq) or are there some other drawbacks to that?

**Comment by Abbe98** [comment]
Maybe a better solution is to check for an end-time qualifier? To sort out non-dead people as well.

If needed one could set up a maintenance query which then would check for dead people with position held but no end-time.

**Comment by Ainali** [comment]
We already check if they have an end date. The problems on these are that they have neither start nor end dates. Should we only allow them to be shown if they do have a start date? That would probably filter out many of these old odd cases.

**Comment by Ainali** [comment]
Thinking a bit more, is there any argument **for** allowing dead people to be displayed as they are leading an organizaiton?

**Comment by Abbe98** [comment]
> Thinking a bit more, is there any argument for allowing dead people to be displayed as they are leading an organization?

Only that we don't discover such issues. 

To me, it feels like ducktape as both the cases were discovered and fixed. I would argue that such cases should be avoided through data improvements. Maybe we can turn the following query into something more Govdirectory specific?

```
SELECT ?person ?personLabel WHERE {
  ?person wdt:P570 [] ;
          wdt:P39 [] ;
          p:P39 ?positionStatement .
  MINUS { ?positionStatement pq:P582 [] }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

LIMIT 1000
```

**Comment by Ainali** [comment]
> Only that we don't discover such issues.

I don't see that as a drawback for Govdirectory. There is no reason why _we_ should discover and fix data that is outside our scope (dead people cannot be contacted). If we take that upon us, we are on a slippery slope to single-handedly fix every data inconsistency in Wikidata. We fixed two cases that were found, but we don't know how many more there are in our data, considering that there seem to be at least tens of thousands of results on your query.

**Comment by Ainali** [comment]
I just did a quick check of the first 20 hits in [this query](https://w.wiki/5m9D). [Flesberg](https://www.govdirectory.org/norway/Q93633/), [Tønsberg](https://www.govdirectory.org/norway/Q107392/), [Åmot](https://www.govdirectory.org/norway/Q271063/), [Levanger](https://www.govdirectory.org/norway/Q216430/) and [Fauske](https://www.govdirectory.org/norway/Q48696/) all have dead people leading them.
I think we're taking on an impossible task if we aim to fix these in data rather than making a more fitting query.

**Comment by Abbe98** [comment]
I'm convinced!
