### ISSUE TITLE
Get Govdirectory onto Mastodon!

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#224]
### Description

We could have it repost things from the Twitter account(or the opposite way around?!).

We would need to select an instance.

**Comment by Abbe98** [comment]
> We would need to select an instance.

I would be happy with mastodon.social och mastodon.online as these are stable and controlled by an NGO but maybe there is a stable one matching Govdirectory well?

**Comment by Ainali** [comment]
One that I come to think of is fosstodon.org

**Comment by Abbe98** [comment]
wikis.world is now the obvious one in my opinion!

**Comment by Ainali** [comment]
Done! https://wikis.world/@govdirectory
