### ISSUE TITLE
Figure out how to model topics for agencies

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#23]
To enable filtering of what kind of agency it is like we need in #18 we need a way to model it in Wikidata. There are a number of possible solutions. 

- Use [P101 (field of work)](https://www.wikidata.org/wiki/Property:P101) (like [this](https://www.wikidata.org/wiki/Q2976522#P101))
- Use [P921 (main subject)](https://www.wikidata.org/wiki/Property:P921)
- Create a new property based on the [UN Classification of the Functions of Government](https://en.wikipedia.org/wiki/Classification_of_the_Functions_of_Government)

The last option is probably the best one, and the first one feels like the second best choice.

**Comment by Abbe98** [comment]
A fourth option might be to map UN classification to various P101 targets.

**Comment by Ainali** [comment]
For many it might be doable, but I guess there is nothing to map `04.7 - Other industries` towards and there are a few others that would be hard to find something for. I' rather create these 69 items to use on a new property, and they in turn could have P921 main subject if we can find suitable items to map them to.

**Comment by Abbe98** [comment]
Yeah makes sense!

**Comment by Ainali** [comment]
Made #29 as a possible solution. If the property proposal fails, this issue needs to be reopened.
