### ISSUE TITLE
Add "improve data", "discuss", etc to create issue templates

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#233]
### Description

I noticed that OpenRefine has options during issue creation to go to external links for chat, etc. We should do the same?

 - report a data error?
 - discuss (on Wikidata?)
 - Improve data
 - ...

![Screenshot 2022-09-16 at 14-28-45 New Issue · OpenRefine_OpenRefine](https://user-images.githubusercontent.com/2631719/190641532-84827373-e306-4954-815c-92dbe2cf436c.png)

**Comment by Ainali** [comment]
Here is how OpenRefine is doing it: [.github/ISSUE_TEMPLATE/config.yml](https://github.com/OpenRefine/OpenRefine/blob/master/.github/ISSUE_TEMPLATE/config.yml).

**Comment by Abbe98** [comment]
I think you are right @Ainali!
