### ISSUE TITLE
Hide the "View on a map" button if JavaScript is disabled

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#238]
### Description

The [map page](https://www.govdirectory.org/countries/map/) requires JavaScript. The link from the [country page](https://www.govdirectory.org/countries/) should therefore be hidden if JavaScript isn't supported. We have an existing "need-js" CSS class that can be used.

**Comment by Pranav4399** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it

**Comment by Farelion** [comment]
Hi, ive created pr for this issue https://github.com/govdirectory/website/pull/240
