### ISSUE TITLE
Add official website in TSV export

### ISSUE THREAD

**Issue by PierreMesure** [govdirectory/website#256]
### The feature

In the export that can be downloaded for every country, it would be great if the official website could be present as a new row 😊.

### Why?

I haven't found any other way to extract it from Govdirectory (but maybe I've missed something) and extracting from Wikidata is cumbersome.

The direct need is a website doing automatic analysis of government websites (from an accessibility, privacy and performance perspective) that would like to use Govdirectory as a source for its list of websites to crawl.

**Comment by PierreMesure** [comment]
I'm posting this here after discussing it with @Ainali. Also interested is @marcusosterberg.

**Comment by Abbe98** [comment]
So what the download feature currently does is that it takes the content of the table and provides that as a download. So the easiest solution would be to add the homepage to the table, which I think makes sense too. @Ainali thought or ideas about how it could look?

![Screenshot 2023-01-20 at 12-35-39 Canada](https://user-images.githubusercontent.com/2631719/213686179-a7ff5236-422d-4615-b474-a4d4788f3975.png)

**Comment by Ainali** [comment]
I like the idea! 
It could just be the quite well-used 🌐 icon in the `Platforms` column that links to the website.

**Comment by RVA2869** [comment]
This is also completed. #341

**Comment by Abbe98** [comment]
All the other icons for social media links got a colored background and white front, what background color could we use for a plain website?

**Comment by Ainali** [comment]
Fixed by #389
