### ISSUE TITLE
Plan session for the Wikimania hackathon?

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#28]
Our second sprint occurs during [Wikimania](https://wikimania.wikimedia.org/wiki/Special:MyLanguage/Wikimania) which have a hackathon on Friday, August 13. Do we want to use that opportunity to get some help from the Wikimedia community?

**Comment by Ainali** [comment]
Ideas that we have floated:

- do some user testing
- "host a table"
- have a "getting started" hacking workshop
- give introduction on how to improve the data

**Comment by Ainali** [comment]
The program is now open to add sessions: https://wikimania.wikimedia.org/wiki/2021:Hackathon#Propose_a_project_or_a_session

**Comment by Ainali** [comment]
This could also be an introduction to Snowman, using govdirectory as examples. This would have the benefit of being more general which could attract more people to the session. Having a larger community upstream to this project would be an advantage in the long run.

**Comment by Abbe98** [comment]
Snowman won't get its 0.1.0 release in time (scheduled for late August) so it would be cumbersome for the time being I'm afraid.

**Comment by Ainali** [comment]
Then I think what fit the Hackathon best is to have a "getting started" hacking workshop where we talk about the general architecture of govdirectory and what our short term goals are. Possibly specifically pointing to the ADD A COUNTRY file for those who want to make smallish contributions.

Additionally we could make a signup page for people who are willing to be interviewed. Even just 1-3 interviews would be a great addition.

**Comment by Ainali** [comment]
Session: https://phabricator.wikimedia.org/T287603
Schedule: https://wikimania.wikimedia.org/w/index.php?title=2021:Hackathon/Schedule&diff=119207&oldid=119206

(I'll also setup interview slots.)

**Comment by Ainali** [comment]
And here are the interview slots: https://wikimania.wikimedia.org/wiki/2021:Hackathon/Govdirectory_user_research
