### ISSUE TITLE
Include an "updated"-timestamp on content pages

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#281]
### The feature

Add a the last updated timestamp to all content pages.

### Why?

We currently only provide this date on the statistics page, but for clarity we should provide it on all pages.

**Comment by Ainali** [comment]
Should we put this in the footer, under the list at the bottom of the main section, or perhaps even as high as in the bottom right of the orange infobox?

**Comment by Abbe98** [comment]
Maybe in the orange infobox, as it's closer to the content.

**Comment by Ainali** [comment]
Like this perhaps?
![Skärmbild från 2023-04-24 13-52-23](https://user-images.githubusercontent.com/5566159/234657816-39d4c936-16af-41be-a053-1479065f033c.png)

**Comment by Abbe98** [comment]
Yeah!

**Comment by Abbe98** [comment]
Maybe just `Updated 2023-04-19`?

**Comment by Ainali** [comment]
> Maybe just `Updated 2023-04-19`?

I even made it a bit longer in the pull request, to be very explicit and clear. I'm open to shorten it down if you want, but I think this will cause least confusion.
