### ISSUE TITLE
Display contact page URL (P11266)

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#293]
### The feature

The new property [contact page URL (P11266)](https://www.wikidata.org/wiki/Property:P11266) would be essential to display on the organization pages, even without a detailed view.

### Why?

It often contains a multitude of ways to contact, and sometimes has a contact form which is the only way to contact some organizations.

### Examples and inspiration

[ Q1191459#P11266](https://www.wikidata.org/wiki/Q1191459#P11266): https://dpe.gov.za/contact/

**Comment by RVA2869** [comment]
This one is completed? Or am I missing something?

**Comment by Abbe98** [comment]
You are right!
