### ISSUE TITLE
How to treat Twitter/X?

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#294]
### Description

Should we change the logo and name? 
I am somewhat inclined to remove it too, but it might be too early since there are plenty of organizations that still have an account.

**Comment by Ainali** [comment]
That makes sense, at least from the overview listing. But perhaps we should still list it under the organization as other non-primary social media? 
Should we switch to Mastodon in the lists?

**Comment by Abbe98** [comment]
> But perhaps we should still list it under the organization as other non-primary social media?

Yeah we don't even have an allow-list for those. 

>  Should we switch to Mastodon in the lists?

I'm all for this, in case we have a logo!

**Comment by Ainali** [comment]
Yes, this one is CC0: https://github.com/simple-icons/simple-icons/blob/develop/icons/mastodon.svg

**Comment by RVA2869** [comment]
What is this issue about? Because I'm getting mixed signals. 

1. Drop support for Twitter/X
2. Remove it from platforms icon list

Proposal: What if we sort the social media networks in alphabetical order, with the result that X is moved from the first to the penultimate place (just before YouTube).
And then (no idea if this is possible with the current JS sort-table) we put a maximum number of logos visible from the country page and if there are more with a +.. like the current situation with the accounts without a logo.

**Comment by Ainali** [comment]
That's a fair question. I think my initial question was a bit vague.

So my first question was just, should we change the bird symbol for an X symbol in the countries listing of organizations.  But then I realized, we might want to drop it from that list all together, solving the first problem by not having to worry about it. And I think we should keep that as a scope for the issue. Adding of Mastodon or another platform could be discussed separately, after removing this one.

I also think we agree on this, so just going ahead and removing it from [social-icons.html](https://github.com/govdirectory/website/blob/main/templates/components/social-icons.html) would be the next step.

**Comment by RVA2869** [comment]
@Ainali I would advocate keeping and updating it. Whether we like it or not, it is still the go to for government agencies (among other things). Removing the logo of the second largest social network (on Govdirectory) is a bit odd to me.


> I think we should remove it given that one can only see the content if you are signed in.

This is not true for every account. Large organizations I can read without problems. (verified and normal accounts) But indeed with the smaller ones (that is also relative -5000 followers) Twitter/X asks you to sign up/in.

Practices that other social networks have also done in the past. Facebook, Instagram and LinkedIn

**Comment by RVA2869** [comment]
A new topic in the saga:[ Twitter URLs redirect to x.com](https://arstechnica.com/tech-policy/2024/05/twitter-urls-redirect-to-x-com-as-musk-gets-closer-to-killing-the-twitter-name/) .No "problem" for us but it is again more X and less Twitter.
