### ISSUE TITLE
Too many Twitter/X accounts are displayed

### ISSUE THREAD

**Issue by RVA2869** [govdirectory/website#314]
### Description

This is something strange... [Ministry of Foreign Affairs of the Russian Federation](https://www.govdirectory.org/russia/Q789889/)
It should display at most 4 or 1 (if we take the preferred rank in consideration) [Ministry of Foreign Affairs of the Russian Federation:Q789889](https://www.wikidata.org/wiki/Q789889)

**Comment by Abbe98** [comment]
Strange indeed.

**Comment by Ainali** [comment]
It's not super strange, the `account-data.rq` query yields them all as a result: https://w.wiki/7q$8

**Comment by Ainali** [comment]
This query ( https://w.wiki/7q$e ) checks for best rank and gets rid of the other, but we still get one true and one false on verified.

**Comment by Ainali** [comment]
They show up twice as they have two values on pq:P1552, one of which will be evaluated to false.
See https://www.wikidata.org/wiki/Q789889#Q789889$4CD4EE92-7965-4AC9-8F54-7B42497DA4CC

**Comment by Abbe98** [comment]
I think we should actually drop use of P1552 in the case of Twitter given that one can qualify just by paying.

**Comment by Ainali** [comment]
> I think we should actually drop use of P1552 in the case of Twitter given that one can qualify just by paying.

Good idea, let's do that.

**Comment by Abbe98** [comment]
It doesn't seem like P1552 is very common elsewhere. I got mixed feelings about us using it at all given that it's not signed or verified in Wikidata and something Govdirectory users should probably double check anyway.

Thoughts on removing it entirely?

**Comment by Abbe98** [comment]
Dropped usage of P1552 all together in 4d999134b0ef2d7b1b240a2afb450483e13e8e22 which fixes this, the changes go live later tonight.
