### ISSUE TITLE
Reduce DOM size

### ISSUE THREAD

**Issue by RVA2869** [govdirectory/website#333]
### The feature

Not so much a feature, but we can remove the logos from the country page. (And move them to the agency page)

### Why?

- better performance
- better SEO
- reducing the amount of data that needs to be transferred each time
- ... 

### Examples and inspiration

[Google PageSpeed Insights (Belgium)](https://pagespeed.web.dev/analysis/https-www-govdirectory-org-belgium/pqypijy3m5?form_factor=mobile) 13961 elements
[Google PageSpeed Insights (Sweden)](https://pagespeed.web.dev/analysis/https-www-govdirectory-org-sweden/zgah5xy41t?use_original_url=true&form_factor=mobile) 10469 elements

**Comment by RVA2869** [comment]
[ Avoid an excessive DOM size ](https://developer.chrome.com/docs/lighthouse/performance/dom-size/)

**Comment by Ainali** [comment]
Do you mean our logos or the social media icons?

**Comment by RVA2869** [comment]
> Do you mean our logos or the social media icons?

Yes

**Comment by Ainali** [comment]
I'm sorry for phrasing the question so poorly, I'll try to make it unambiguous by splitting it into two questions: 

1. Do you mean that we should remove our logos?
2. Do you mean that we should remove the social media icons?

**Comment by RVA2869** [comment]
The problem is not so much the (social media) logos/icons, but each of them has a unique link and that is what makes the DOM size so large (among other things). Removing the social media links would be a solution. From the country page, though.😉

**Comment by Ainali** [comment]
Aha. That would add some clicks to get to the link, though, and removing the icons would remove the clue that the org is worth clicking on.
For myself, I often use the country page to get an overview of where works need to be done.

**Comment by Abbe98** [comment]
I would be worried about the DOM parsing we do for the "filtering" feature but it seems to work for now even on slow devices(tested on a Pinephone).

If it becomes a problem we should maybe come up with a better solution to long lists, things like #212 and in the worst case default to pagination.

**Comment by Abbe98** [comment]
Given that #212 is now implemented let's close this for now and if need be open an issue about pagination.
