### ISSUE TITLE
TSV export doesn’t work

### ISSUE THREAD

**Issue by PierreMesure** [govdirectory/website#341]
### What happened?

When trying to download a TSV file for a country’s organisations, the file only contains the column names but no rows.

Downloading a TSV file for a single organisation seems to work fine.

### What browsers are you seeing the problem on?

Safari

**Comment by Ainali** [comment]
I just tested on [Russia](https://www.govdirectory.org/russia/) with Chrome and can confirm that it just downloads the columns.

**Comment by Abbe98** [comment]
Fixed on `main` but not yet deployed.
