### ISSUE TITLE
Get complete coverage of Swedish agencies

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#37]
We should have all current Swedish agencies in the data (not necessarily with all social media accounts). [Currently](https://www.wikidata.org/wiki/Wikidata:Gov_Directory/Sweden) courts and agencies abroad (mostly embassies) are missing.

**Comment by Abbe98** [comment]
on the court side, we are only missing 12 "special courts"! https://w.wiki/3chf

**Comment by Abbe98** [comment]
Or 11 because Domstolsverket is covered by general government agencies in Wikidata I think.

**Comment by Ainali** [comment]
> Or 11 because Domstolsverket is covered by general government agencies in Wikidata I think.

Does that data need to be fixed? They are listed in the courts in Myndighetsregistret.

**Comment by Abbe98** [comment]
It might mean that we are missing a general government agency, but I'm not sure the best match for it is to be a court in Wikidata. Maybe its own type?

**Comment by Ainali** [comment]
No [Domstolsverket (Q10475844)](https://www.wikidata.org/wiki/Q10475844) is not a [Swedish government agency (Q68295960)](https://www.wikidata.org/wiki/Q68295960) so we shouldn't be missing anything else.

**Comment by Abbe98** [comment]
Ah, true!

**Comment by Ainali** [comment]
Should be completed now and can be reviewed through this query: https://w.wiki/3szL

**Comment by Ainali** [comment]
My changes for the municipalities has been reverted (perhaps temporarily, pending the [discussion](https://www.wikidata.org/wiki/Property_talk:P1366#Using_the_property_when_the_item_is_not_dissolved)).

**Comment by Abbe98** [comment]
Should we give one last ping before reintroducing our changes? We are still missing 12 municipalities.

**Comment by RVA2869** [comment]
I thought: "this should be easy to solve".... If only you had used a reference on the project page. 😉 (I don't want to point fingers, but... 👈 👇 👉 ☝️ )
Current state: `# expected_result_count: 766 - 768 found`

**Comment by Abbe98** [comment]
Hehe, I think in general the last mile will always be a pain. I know Gotland is an issue because people keep setting it to "region" but the ~3 other doesn't seem to be municipalities anymore.
