### ISSUE TITLE
Add a publiccode.yml file

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#371]
### The feature

Publiccode.yml is a metadata file describing the codebase and the governance.

### Why?

This will make it possible for the codebase to be picked up by the various scrapers that are creating catalogs of software using this file as a base.

While this is not perfectly fitting (as it is not, to our knowledge, specifically used by any public organization), it will still likely make it easier for people to both find the project, and understand it.

It will also meet the last requirement under [Make the codebase findable](https://www.govdirectory.org/standard-for-public-code/#make-the-codebase-findable) in the Standard for Public Code.

### Examples and inspiration

Examples:

- [Libre Office](https://github.com/tdf/libreoffice-metadata/blob/master/publiccode.yml)
- [PDF Sam](https://github.com/torakiki/pdfsam/blob/master/publiccode.yml)
- [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks/blob/main/publiccode.yml)

Tool to create a publiccode.yml file: [Web editor](https://publiccode-editor.developers.italia.it/)

**Comment by RVA2869** [comment]
more info: [https://yml.publiccode.tools/](https://yml.publiccode.tools/)

**Comment by Abbe98** [comment]
Closed by #378
