### ISSUE TITLE
Add citation file

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#373]
### The feature

We should add a [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file to the root directory that displays citable metadata in a well-defined way.

### Why?

This makes it easier for anyone who would like to cite this repository / website. GitHub has support for the file type and will show a button, and also Zotero's browser plugin can pick it up.

### Examples and inspiration

A couple of repositories using the file:

- [pandoc](https://github.com/jgm/pandoc/blob/a0c1bdeb8b93e2661132a714668dff5f32ffb167/CITATION.cff#L4)
- [TensorFlow](https://github.com/tensorflow/tensorflow/blob/161d9f2f9964c4a5860f0dd57ea584c337d95d6a/CITATION.cff)
- [The Turing Way](https://github.com/the-turing-way/the-turing-way/blob/main/CITATION.cff)

**Comment by RVA2869** [comment]
Tool to generate the citation.cff file: [cffinit](https://citation-file-format.github.io/cff-initializer-javascript/#/)

**Comment by Ainali** [comment]
Fixed by #374
