### ISSUE TITLE
Website icon is not showing.

### ISSUE THREAD

**Issue by RVA2869** [govdirectory/website#392]
### What happened?

The website icon is displayed only if a social media platform is present.

**Comment by Ainali** [comment]
Do you have an example where it should be shown, but is not?

**Comment by RVA2869** [comment]
> Do you have an example where it should be shown, but is not?

[Sjätte AP-fonden](https://www.govdirectory.org/sweden/Q33075659/)
[Health and Disability Commissioner](https://www.govdirectory.org/new-zealand/Q5690737/)
[Bütgenbach](https://www.govdirectory.org/belgium/Q160005/)

**Comment by Abbe98** [comment]
Thank you @RVA2869!
