### ISSUE TITLE
Recently added accounts still appear in the 'Recently Updated' section after seven years

### ISSUE THREAD

**Issue by RVA2869** [govdirectory/website#406]
### What happened?

No idea how widespread this issue is.

[Department of Environment and Natural Resources](https://www.govdirectory.org/philippines/Q3277331/)
[Wikidata history](https://www.wikidata.org/w/index.php?title=Q3277331&diff=468024559&oldid=468024499)

**Comment by Abbe98** [comment]
For some reason the account isn't returned by our account-data.rq query:

https://w.wiki/Aig7

**Comment by Abbe98** [comment]
Looks like a Wikidata bug, according to the RDF the X account got an end-time: https://www.wikidata.org/wiki/Special:EntityData/Q3277331.rdf

**Comment by Abbe98** [comment]
Looks like the recently added feature does not take end-time into account.

**Comment by RVA2869** [comment]
> Looks like the recently added feature does not take end-time into account.

I didn't even notice there was an end date -_-
related question: does the end date qualifier also remove social media pages from the website?

**Comment by Abbe98** [comment]
Yes, that should be the case.
