### ISSUE TITLE
Dutch prime minister not updated

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#407]
### What happened?

On https://www.govdirectory.org/netherlands/ it still says the old one, while Wikidata was updated 6 July: https://www.wikidata.org/w/index.php?title=Q55&diff=2197041992&oldid=2194816745

I am guessing that might have to do with just a partial updated of the data, but it is a bit confusing then that the page says "Data last updated 2024-07-12.". 

I am not sure what the best solution is. Is it possible to only update the "Data last updated" string on pages that got updated?

**Comment by RVA2869** [comment]
yes, I have noticed this too (in various countries and agencies).

> Is it possible to only update the "Data last updated" string on pages that got updated?

This should be the default. 

Related: Ultimately we need to separate the version numbers/dates into: when the code changed, when there is a change at country level, and at agency level. 

[https://www.govdirectory.org/standard-for-public-code/](https://www.govdirectory.org/standard-for-public-code/)
[https://standard.publiccode.net/criteria/document-codebase-maturity.html](https://standard.publiccode.net/criteria/document-codebase-maturity.html)

**Comment by Ainali** [comment]
> Related: Ultimately we need to separate the version numbers/dates into: when the code changed, when there is a change at country level, and at agency level.
> 
> https://www.govdirectory.org/standard-for-public-code/ https://standard.publiccode.net/criteria/document-codebase-maturity.html

We haven't made a commitment to be fully compliant, so it is not a necessary. That said, I think we should be as clear as possible.

(Right now, the Standard for Public Code also lacks good guidance or examples for how websites like ours without version releases should show the maturity in a way that is deemed compliant. If that gets published, we should take a second look at that requirement.)

**Comment by RVA2869** [comment]
Is there a reason why there is a partial update instead of a full update?

Maybe an automatic update (e.g. every first of the month) is a solution?

**Comment by Abbe98** [comment]
> Is there a reason why there is a partial update instead of a full update?

Being nice to the query service, as we don't really update weekly anymore I'm not that it's as important as before.

> Maybe an automatic update (e.g. every first of the month) is a solution?

Yes this would be the best solution, I have seen it tied to a migration to Wikimedia Cloud(#33) in the past but there is not much of a good reason to do so frankly.

**Comment by Ainali** [comment]
Closing this as the Dutch prime minister is updated now.
