### ISSUE TITLE
How do we address the issue when there are multiple ministers in one ministry?

### ISSUE THREAD

**Issue by RVA2869** [govdirectory/website#417]
### Description

Currently, the infobox shows only 1 value.

I came across this one in Canada.
[GD:Innovation, Science and Economic Development Canada](https://www.govdirectory.org/canada/Q1057600/)
The 5 ministers: [https://ised-isde.canada.ca/](https://ised-isde.canada.ca/site/ised/en#Corporate_information)
Of course, the property ([office held by head of organization P2388](https://www.wikidata.org/wiki/Property:P2388)) has not yet been added.

Same issue here:
[GD:Federal Public Service Foreign Affairs](https://www.govdirectory.org/belgium/Q137670/)
[https://www.wikidata.org/wiki/Q137670#P2388](https://www.wikidata.org/wiki/Q137670#P2388)

**Comment by Ainali** [comment]
From English Wikipedia: "The department at large is headed by the minister of innovation, science and industry, François-Philippe Champagne."

And I think this will be a general solution. Even if there are several ministers in a department, one of them will be the head of it. For example, The Swedish Ministry of Climate and Enterprise has two ministers, but it is led by one of them.

**Comment by Ainali** [comment]
Closing this for now, reopen if we find other complex ministries with no clear leader.
