### ISSUE TITLE
Add basic navigation bar

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#42]
We have a rough draft that should be added to the layout template. Current design:

![Skärmbild från 2021-07-10 14-44-45](https://user-images.githubusercontent.com/5566159/125163426-679e5480-e18d-11eb-857c-2debd8addffb.png)

@Abbe98 Should this wait until we have something to show on the country and subject pages or should I add it with only the first two links?

**Comment by Abbe98** [comment]
I would suggest adding it with only two links, it might be useful for user testing/retrieval tasks.
