### ISSUE TITLE
Add fediverse creator tag

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#426]
### The feature

We should add the [fediverse creator tag](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/) that got added in the [Mastodon 4.3 release](https://blog.joinmastodon.org/2024/10/mastodon-4.3/#helping-writers-and-journalists). For us, I believe it would look like:

`<meta name="fediverse:creator" content="@govdirectory@wikis.world" />`

and I think the right place to put it would be in templates/layouts/layout.html.

### Why?

This would increase discoverability of the Mastodon account when links are being shared on the fediverse.

### Examples and inspiration

See examples in the first link above.

**Comment by Ainali** [comment]
(Note: Author attribution for the domain govdirectory.org has already been enabled in our Mastodon account.)

**Comment by Abbe98** [comment]
I'm curious, are there other examples of it being used to reference brand/website accounts?

**Comment by Ainali** [comment]
> I'm curious, are there other examples of it being used to reference brand/website accounts? This usage seems more like a self reference to me similar to the intent of `rel="me"`.

I haven't seen any in the wild yet, which can be explained by it being a new feature.
But the difference from rel=me is that if someone would share any link from govdirectory, let's say `https://www.govdirectory.org/germany/Q491637/` then the link preview window on Mastodon would have a bottom bar with "More from [Govdirectory](https://wikis.world/@govdirectory)" on it. So, rather than verifying an account through one link, it's giving discoverability of it through many links.

**Comment by Abbe98** [comment]
The feature has been around for a few months and I see it quite often but never in this way. It has always been used to point to the creator of a specific work not globally for a brand/website, the documentation also use it in the former way.

**Comment by Abbe98** [comment]
> I think that before 4.3 it was only available as an experiment for a few media houses, who used it for the accounts of their journalists on the media house's self-hosted Fediverse instances.

No it has been available for everyone for at least a few months, it has just not been visible for Mastodon instances not following the nightly builds. 

> Either way, I don't see why that matters? The documentation does not say that it has to point to a personal account or that it cannot point to only one account.

We do have a system for this particular use and the intent with this new one seems different so I could imagine this practically being abuse. That's why I'm asking for examples where it's being used in a similar fashion to what's proposed here, I wouldn't want to be the outlier...

**Comment by Ainali** [comment]
I find it unlikely someone would think it is abuse, we put a relevant value of the expected type in that tag. And it looks like the man working on the documentation of the feature also [thinks it is ok](https://macaw.social/@andypiper/113349931446860635).

**Comment by Abbe98** [comment]
That's good enough for me!
