### ISSUE TITLE
Add some sort of web analytics

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#45]
[Plausible](https://plausible.io/) is a "lightweight and open-source website analytics tool. No cookies and fully compliant with GDPR, CCPA and PECR. Made and hosted in the EU", perhaps we can use that to get some insights in how the website gets uesd?

[Example on a real cloud hosted version.](https://plausible.io/publiccode.net)

**Comment by Abbe98** [comment]
Is there something like this on WM Cloud maybe?

**Comment by Abbe98** [comment]
Alternatively, check if we can piggyback on a chapter's Matomo instance.

**Comment by Ainali** [comment]
> Alternatively, check if we can piggyback on a chapter's Matomo instance.

Yes, that would be easier for maintenance. Is there anyone willing providing hosting and login details to their instance? 

One bonus of Plausible is that you can have it publicly viewable, I have no clue if that is possible in Matomo, but it is also not a dealbreaker.

**Comment by Ainali** [comment]
Apparently [Wikimedia has Matomo](https://wikitech.wikimedia.org/wiki/Analytics/Systems/Matomo). But I guess this is hinging on #33.

**Comment by Abbe98** [comment]
WMDE and WMSE also got Matomo instances.

**Comment by Ainali** [comment]
Application to WMSE has been submitted: https://se.wikimedia.org/wiki/St%C3%B6d_till_gemenskapen/Projektst%C3%B6d/Tillg%C3%A5ng_till_analysverktyg_f%C3%B6r_Wikidatadrivet_projekt

**Comment by Abbe98** [comment]
Implemented in c1880394643c1b5376f3d6ebe8c7736d870e542d. Note that it lacks subresource integrity checks because upstream lacks CORS.
