### ISSUE TITLE
Consider an "add my country" workshop for Wikimedia CEE Online Meeting 2021

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#54]
[Wikimedia CEE Online Meeting 2021](https://meta.wikimedia.org/wiki/Wikimedia_CEE_Online_Meeting_2021/Submissions) has a deadline on August 31

**Comment by Abbe98** [comment]
I think this is a great idea!

**Comment by Abbe98** [comment]
Proposal fields: 

- Title of the submission
- Type of submission (lightning talk, discussion, panel, workshop)
- Author(s) of the submission
- Username(s)
- Affiliation
- Theme(s)
- Level of advancement (basic, medium, advanced)
- Abstract (up to 100 words)
- How will this session be beneficial for the communities in the region of Central and Eastern Europe?
- Do you plan to pre-record a video with a presentation?
- Special requirements
- Slides or further information

**Comment by Ainali** [comment]
Suggestion:
- Title of the submission
  - Add your country to the Wikidata Govdirectory
- Type of submission (lightning talk, discussion, panel, workshop)
  - workshop
- Author(s) of the submission
  - Abbe98 and Ainali
- Username(s)
  - Abbe98 and Ainali
- Affiliation
  - None
- Theme(s)
  - Wikidata project
- Level of advancement (basic, medium, advanced)
  - basic 
- Abstract (up to 100 words)
  - This session will be a hands-on workshop for adding a country to [[d:Wikidata:WikiProject Govdirectory]]. We will cover what kind of general information and sources that would be beneficial to document. We will also help writing queries in order to be able to review if the data in Wikidata is complete and correct.
- How will this session be beneficial for the communities in the region of Central and Eastern Europe?
  - This will be a flying start to get any country in the Central and Eastern Europe ready to be listed in the Govdirectory. This is also great preparatory work for other projects like WikiProject Every Politician or WikiProject Open Government Data since the basic structures of all public agencies will be reviewed.
- Do you plan to pre-record a video with a presentation?
  - No
- Special requirements
  - None
- Slides or further information
  - [[d:Wikidata:WikiProject Govdirectory]]

**Comment by Ainali** [comment]
Does it look good?

**Comment by Abbe98** [comment]
Looks good! Maybe it's medium level of advancement(I'm not sure at all)?

**Comment by Ainali** [comment]
I think you are right. Let's go with that.

**Comment by Ainali** [comment]
Submitted: https://meta.wikimedia.org/wiki/Wikimedia_CEE_Online_Meeting_2021/Programme/Submissions/Add_your_country_to_the_Wikidata_Govdirectory
