### ISSUE TITLE
Decide which platforms to display in results views

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#55]
The results views will have one row for each organization where we want to display some icons to indicate if an organization has an account on one of the more common platforms. We probably want to support this for about 3-5 platforms which we need to pick.

Some canidates:
 - Facebook
 - YouTube
 - Instagram
 - LinkedIn
 - WeChat
 - Telegram
 - Twitter
 - TikTok

**Comment by Ainali** [comment]
My intuition is that Twitter, LinkedIn and Facebook will be those with highest coverage in Europe and North America. V Kontakte is large in countries where people understand russian. This site has some nice stats (also over time): https://vincos.it/world-map-of-social-networks/

Question: Should this be defined by country or would it add a lot more work than having the same choice globally?

**Comment by Abbe98** [comment]
Initially, I think we should aim for a global choice but it should not be an enormous task to have it configurable in [countries.rq](https://github.com/govdirectory/website/blob/main/queries/countries.rq (maybe as a way to override the default).

**Comment by Abbe98** [comment]
This does not work globally but maybe we could compare a few different countries https://w.wiki/3enY

**Comment by Ainali** [comment]
Nice! I noticed that LinkedIn was missing, so I [fixed that](https://www.wikidata.org/w/index.php?title=Property:P4264&diff=prev&oldid=1462970562).

**Comment by Abbe98** [comment]
https://github.com/govdirectory/website/commit/8f608e161f2bbb78cbffc8741b41497ecc5b4d80 implemented Twitter, YouTube, LinkedIn, Facebook, and Instagram for now.

**Comment by Abbe98** [comment]
Closing this, it can be reevaluated at a later stage.
