### ISSUE TITLE
Replace issuer with a better property for retrieving platform name

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#56]
Currently, the website uses the issuer property to retrieve the platform name from the identifier property but often and rightfully the issuer points to the company running the platform. Causing bugs like Facebook being called "Facebook Inc" or TikTok being named ByteDance.

An option to the issuer property is to use P:subproperty of->Q:website username->P:of->"platform", it has the downside that its more expensive to retrieve and that it uses the questionable "of" pattern. Anyway, we would need to add the data for each identifier property.

**Comment by Ainali** [comment]
Perhaps a more elegant than 'of' would be to add [used by (P1535)](https://www.wikidata.org/wiki/Property:P1535) to point directly to the platform?

Still some work to be done, but it seems like good modeling and is simpler to query for.

**Comment by Abbe98** [comment]
I think that it would indicate that the property is used by a certain platform instead of the identifier itself.

 Existing use seems to manly use it in such a manner. Properties seem to mainly use it to connect MediaWiki templates that depend on the properties: https://w.wiki/3emE

**Comment by Ainali** [comment]
Ah, you are right. The 'used by' would be more appropriate if we had an item for the id. Hmm, then my suggestion isn't really appropriate.

**Comment by Abbe98** [comment]
"Wikidata item of this property" (P1629) is another option, however it might not nessisarly point to the item of the platform but of the identifier which would force us to check the instance of the target item anyway. Seems odd that a property can have different types of target items/meaning whithout an qualifier.

**Comment by Ainali** [comment]
P1629 seems like a good idea, but as you said, unfortunately the data looks kind of messy: https://w.wiki/3g5W

But perhaps that is good enough to get us started and to cleanup some data?

**Comment by Abbe98** [comment]
The site now uses the subproperty pattern. Platforms which needs this data on Wikidata: https://w.wiki/3gcz
