### ISSUE TITLE
Setup Ping project and Participants templates on Wikidata

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#60]
We might need to move the project from Wikidata:Gov_directory to Wikidata:WikiProject_* as the templates seem to have hardcoded the WikiProject part but I'm not sure.

https://www.wikidata.org/wiki/Template:Participants
https://www.wikidata.org/wiki/Template:Ping_project

**Comment by Ainali** [comment]
Oh, a bit unexpected, but I guess that is worth it.

**Comment by Ainali** [comment]
The pages have been moved. Proceeding to setup a participants page.

**Comment by Ainali** [comment]
Solved with https://www.wikidata.org/wiki/Wikidata:WikiProject_Govdirectory/Participantsand  https://www.wikidata.org/w/index.php?title=Wikidata%3AWikiProject_Govdirectory&type=revision&diff=1464785905&oldid=1464302691
