### ISSUE TITLE
Add link to start/join discussions

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#65]
We should also have a generic comment somewhere to direct people with general questions to discussions/Wikidata.

_Originally posted by @Abbe98 in https://github.com/govdirectory/website/issues/10#issuecomment-870006460_

This also came up as an idea after interviewing. We should possibly have separate entry points if someone wants to discuss the data or if someone wants to discuss the govdirectory website.

**Comment by Abbe98** [comment]
For data issues the best place would maybe be the item's discussion pages maybe we could have a template so we can discover discussions on any page orginating from Govdirectory.

**Comment by Ainali** [comment]
Yes, most likely for the data is that someone spotted something questionable, but not having a source with any better data. So perhaps we have one "data" link on each page that goes to the talk page of that Q-id. If the user is on any kind of list page with several items, it goes to a "helpdesk" on Wikidata. And then we have some sort of platform discussion link that goes to github discussions.

Or, it's just one button that gives you a multiple choice which then posts it to the right place.

**Comment by Abbe98** [comment]
Note to self:
https://www.wikidata.org/w/api.php?action=edit&format=json&title=Wikidata_talk%3AWikiProject_Govdirectory&section=new&sectiontitle=Q34&text=This%20is%20a%20test.%20~~~~&summary=Edit%20through%20the%20API&token=

**Comment by Abbe98** [comment]
> Users who are not logged in will always be given the empty CSRF token, `+\`.

https://www.mediawiki.org/wiki/API:Edit#Additional_notes

**Comment by Ainali** [comment]
There is an easier way to do it without the API, thanks to the `section=new` functionality in the edit action:

https://wikidata.org/w/index.php?title=Wikidata:WikiProject_Govdirectory/Error_reports&action=edit&section=new

**Comment by Ainali** [comment]
Fixed for now by #185
