### ISSUE TITLE
Make design for lists

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#71]
We have lists in several places and they should share as much of the design as possible. We have lists on pages of these types with the list items in parenthesis:

- [ ] Country (institutions)
- [ ] Topic  (institutions)
- [ ] Institution (accounts)

**Comment by anevski-stefan** [comment]
Is this still open issue? It would be my first collaboration so I would want to accept that if it's still open

**Comment by Ainali** [comment]
@anevski-stefan  Good question. In a sense, we already have lists, as can see on https://www.govdirectory.org/ on the various types. But I guess they could still be aligned and improved a bit. Please, take a look if you can see any room for improvement, and if you are unsure, just discuss here.
