### ISSUE TITLE
Design page hierarchy for topics  

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#74]
COFOG got a hierarchy consisting of four levels.

- should we expose all of them or make an abstraction
- should the topic page lead to more topic pages three times before a result is given
- etc.

**Comment by Ainali** [comment]
I think we should expose all since not all agencies are on the lowest level. Looking at the Swedish data there seems to be agencies assigned on the highest or the lowest levels. So my thinking right now is that we show them on the level that the official source place them on. (Also I only get it to three levels, for example 04, 04.1 and 04.1.1)

It would be really neat if if each label had the sum of agencies underneath it. Like `Defence (230)`.

**Comment by Abbe98** [comment]
I was more thinking in the lines of abstracting it to only use the first
level, all agencies will have it and the titles are short and
understandable by most. This would be a nice area to experiment with what
users expect.

Selecting **05 - Environmental protection**would return the following
Swedish agencies:

- Havs- och vattenmyndigheten
- Polarforskningssekretariatet
- Kemikalieinspektionen
- Naturvårdsverket

The last one "Naturvårdsverket" might be considered the major one in
Sweden, it's under "Environmental protection n.e.c." together with
"Kemikalieinspektionen".

Maybe top-level various should just behave as a result view which can be
filtered(in table) by the lower-level classifications, that way no agency
gets "hidden" at the same time as all classes are communicated.






Den lör 31 juli 2021 kl 23:49 skrev Jan Ainali ***@***.***>:

**Comment by Ainali** [comment]
Ah, I see your point. That sounds like a good idea, and it also makes it easier to get started since it will be less complex. Let's go with that fo now and then we can think of hierarchies and filtering later.

**Comment by Ainali** [comment]
This also means that if we have the 10 circles on the main page, we don't need a "Topics" page where we repeat them, but that clicking one of those will take you directly to the topic in question. The downside with that is that it might be a good feature to link someone directly to a topics listing (but for now that can be solved with an anchor on the main page).

**Comment by Abbe98** [comment]
I don't think duplicating it is an issue.

**Comment by Ainali** [comment]
Ok, then let's have a "Topics" page too then. That will lay the foundation if we want to test subcategories later.

**Comment by Ainali** [comment]
I guess this issue is solved then, by only having the top level, no real hierarchy is needed for now.
