### ISSUE TITLE
Make a COFOG import

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#77]
When the proposal in #29 gets approved (which looks very promising), we should create items for each of the classifications and connect them properly in the intended hierarchy. That will both enable us adding them to agencies, and later also to query for them.

Q: Which property should connect items of lower and higher levels? Just subclass of (P279)? 

- [x] We need a new item that can be used as P31 on all the other ones. 
- [x] Figure out what statements to add to the classification items
- [x] Prepare quickstatements import
- [x] Run the import

**Comment by Abbe98** [comment]
Do the items need P31, considering that they are concepts in a vocabulary rather than "things"?

**Comment by Ainali** [comment]
I a not sure, but I think that would be useful, similar to how [Target 4.1 of the Sustainable Development Goals (Q57590772)](https://www.wikidata.org/wiki/Q57590772) is an instance of [Sustainable Development Goal Target (Q56724848)](https://www.wikidata.org/wiki/Q56724848). That modeling makes querying very easy.

**Comment by Abbe98** [comment]
Indeed querying becomes easier but the SDG Targets are actual targets rather than concepts.

**Comment by Ainali** [comment]
Sure but there are plenty of things that are subclass of concept in Wikidata so that's not a major concern: https://w.wiki/3n2i

**Comment by Ainali** [comment]
A property creator [wanted us to do this before the property is made](https://www.wikidata.org/w/index.php?title=Wikidata:Property_proposal/Classification_of_the_Functions_of_Government&diff=1480799535&oldid=1480798473) so I'll start working on this since it apparently this blocking #29 and not the other way around.

**Comment by Ainali** [comment]
The import has been done. The items need still to be connected with each other and get main subjects, but all the items are created with some basic info.
