### ISSUE TITLE
Hide accounts having end-time set

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#83]
Sometimes account-statements un Wikidata has an end-time Govdirectory.org should not display these.

The [account-data query](https://github.com/govdirectory/website/blob/main/queries/account-data.rq) should be modified so that it does not return account's having an end-time.

https://www.wikidata.org/wiki/Q1172261
https://www.govdirectory.org/sweden/Q1172261/

**Comment by viveknshah** [comment]
Id like to give this a shot.

**Comment by viveknshah** [comment]
Would I be on the right track with the following condition? 

FILTER(?P582_0 < "now()"^^xsd:dateTime)

Dont see too much material out there with date manip in WikiData so trial and error.

**Comment by Ainali** [comment]
@viveknshah You can always try the query on https://query.wikidata.org/ 
And there you can also find some queries with date manipulation, try searching for `now()`or `xsd:dateTime` in the filter box in Examples.

**Comment by Ainali** [comment]
Fixed by #247
