### ISSUE TITLE
Text from Wikidata should have a `lang` attribute

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#84]
Snowman exposes the language of all Literals like so: `.Variable.Lang`, therefore in places where a non-English literal could be expected(names, etc) make sure the tag containing the literal has `lang` set.

Example change:
```
- <h1>{{ .orgLabel }}</h1>
+ <h1 lang="{{ .orgLabel.Lang }}">{{ .orgLabel }}</h1>
```

**Comment by toukirkhan** [comment]
I think I can solve this issue please assign me this.
