### ISSUE TITLE
Report an error button?

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#87]
Should we have a button for reporting an error? It might be to high bar to actually edit Wikidata, but just appending a message on the talk page might be easier.

**Comment by Abbe98** [comment]
One user-testing session has so far indicated that "report" would be better than "edit".

**Comment by Ainali** [comment]
A page for the reports to "land on" has been set up: https://www.wikidata.org/wiki/Wikidata:WikiProject_Govdirectory/Error_reports

A new section can be created through this:  https://wikidata.org/w/index.php?title=Wikidata:WikiProject_Govdirectory/Error_reports&action=edit&section=new

There are more advanced things one can do that give a modal window with help text (as used in several places on Meta, but that requires Lua modules), but this is at least a start.

**Comment by Abbe98** [comment]
Nice, one problem is if there is no Wikipedia link to an agency where do we put the Wikidata logo/link? Should it be floating on its own or do we need to rethink its position?

**Comment by Ainali** [comment]
I think perhaps we should rethink all the buttons. Perhaps they don't need a big header.  If we can make them more compact and self explaining, it would also be easier to place them dynamically.

**Comment by Abbe98** [comment]
Yeah something in the style of what Fabian suggested.

**Comment by Abbe98** [comment]
With a bit of help I was able to find a good solution for creating error reports as well:

https://www.wikidata.org/w/index.php?action=edit&title=Wikidata:WikiProject_Govdirectory/Error_reports&section=new&preloadtitle=Error+regarding+Q2&preload=Wikidata%3ASandbox

We could point the preload to a page like "Wikidata:WikiProject_Govdirectory/Error_reports/Error_body_template".

**Comment by Ainali** [comment]
Suggestion, we use the symbol `embassy` from Maki (a flag) and put it on a white circle next to the Wikidata icon. A tooltip could be "Discuss the displayed data on Wikidata"

![Skärmbild från 2022-02-04 23-39-27](https://user-images.githubusercontent.com/5566159/152613581-c7c0e3bf-2dd8-4e61-8834-3e9191fa9b4f.png)

**Comment by Abbe98** [comment]
That's a great idea!
