### ISSUE TITLE
Create Code for All lightning talk

### ISSUE THREAD

**Issue by Ainali** [govdirectory/website#88]
This talk should be a 5-7 minute long pre-recorded video. Our submission is in #53.

**Comment by Ainali** [comment]
I suggest we record this in Streamyard. I think we can mostly reuse [the presentation from Wikimania](https://docs.google.com/presentation/d/1X0j0WVlrcFnPhg8JEZBpBBE_NbH-kiXHkFdXvklTIR8/edit?usp=sharing) but should probably coordinate a bit better who says what and present ourselves a bit in the beginning.

**Comment by Abbe98** [comment]
Considering the time limit, what about something like the following?

 - What is Wikidata
 - Get data from Wikidata (civic tech examples WDQS+short links) 
 - Govdirectory (what/how)
 - Learn more (links Wikidata/Govdirectory)

**Comment by Ainali** [comment]
The talk has been recorded and submitted. The presentation used is available at https://bit.ly/wikidatacivictech
