### ISSUE TITLE
Implement topics

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#90]
- [x] a page similar to the countries page with the 10 upper-level classes
- [x] pages for each topic similar to individual language pages (display subclass, country, social)

- [x] link to the topic from org pages
- [ ] link to the topic from country page tables

**Comment by Abbe98** [comment]
Generator for generation of new pages:

```sparql
SELECT DISTINCT * WHERE {
  VALUES (?class ?safeName ?label) {
    (wd:Q108107925 "general-public-services" "General Public Services")
    (wd:Q108107955  "defense" "Defense")
    (wd:Q108107969 "" "")
    (wd:Q108107990 "" "")
    (wd:Q108108058 "" "")
    (wd:Q108108075 "" "")
    (wd:Q108108099 "" "")
    (wd:Q108108141 "" "")
    (wd:Q108108158 "" "")
    (wd:Q108108190 "" "")
  }
} ORDER BY ?class
```

**Comment by Ainali** [comment]
In a first draft I used the following icons from the maki icon library:

- Economic affairs: bank.svg
- Defence: castle.svg
- Education: college.svg
- Health: defibrillator.svg
- Environmental protection: garden.svg
- General public services: museum.svg
- Public order and safety: police.svg
- Recreation, culture and religion: theatre.svg
- Social protection: toilet.svg
- Housing and community amenities: town.svg

![Skärmbild från 2021-08-16 22-23-48](https://user-images.githubusercontent.com/5566159/129625521-b39b82ea-ac55-4e7a-a4af-5407b7349608.png)

**Comment by Abbe98** [comment]
Icon-based design implemented in https://github.com/govdirectory/website/commit/cc49f36c4e24e0cd486f31e75b113c03e1552945.

**Comment by Abbe98** [comment]
The COFOG labels don't work well as button labels as they can be rather long. We could create new labels for each top-level class or render the link as a text link instead of a button link. 

![Screenshot from 2021-08-22 22-45-07](https://user-images.githubusercontent.com/2631719/130369568-50776b1d-d18f-443d-8015-d87bd6b56402.png)

**Comment by Ainali** [comment]
@Abbe98 Should we close this as completed? (We also have [#270 Alternative approach to topics](https://github.com/govdirectory/website/issues/270) for the continued work.)

**Comment by Abbe98** [comment]
Yes!
