### ISSUE TITLE
All images should have explicite height and width to reduce cumulative layout shift

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#96]
We should on all `img` tags have the `height` and `width` attributes to limit cumulative layout shift after CSS and images are loading.

Review all `img` tags and give them `height` and `width` attributes.

**Comment by Abbe98** [comment]
As an example some of the issues were addressed in https://github.com/govdirectory/website/commit/e36d8e824a46d8e3bd69c1f57333133da6c24980.

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it.

**Comment by Ainali** [comment]
Let's do one at a time, I assigned #137 to you.

**Comment by Ezekiel8807** [comment]
i can also work on this, if there is any you can assign it to me

**Comment by Ezekiel8807** [comment]
Thanks man....  I'm now on it

**Comment by aarishmkhan** [comment]
Hey, I can work on this issue. Assign it to me please

**Comment by aarishmkhan** [comment]
How do I setup a local WDQS instance?
